import type { Metadata } from "next";
import "./globals.css";
import { Mulish } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

export const metadata: Metadata = {
   title: "Finace Ai",
   description: "Generated by create next app",
};

const mulish = Mulish({
   subsets: ["latin-ext"],
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ClerkProvider
         appearance={{
            baseTheme: dark,
         }}
      >
         <html lang="en">
            <body className={`${mulish.className} antialiasedt dark`}>
               <div className="flex h-full flex-col overflow-hidden">
                  {children}

                  <Toaster />
               </div>
            </body>
         </html>
      </ClerkProvider>
   );
}
