import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const inter = Inter({
   subsets: ["latin"],
   display: "auto",
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${inter.className} antialiasedt dark`}>
            <ClerkProvider
               appearance={{
                  baseTheme: dark,
               }}
            >
               {children}
            </ClerkProvider>
         </body>
      </html>
   );
}
